# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.network :public_network
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  config.vm.synced_folder "../salt_roots", "/srv"
  config.vm.provision :salt do |salt|
    salt.minion_config = "../minion"
    salt.pillar( {
                   "checkout" => {
                     "repo" => "git@github.com:jspc/super-thing.git",
                     "sha"   => `git log | head -1 | awk '{print $2}'`
                   }
                 } )
    salt.run_highstate = true
  end
end
