# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.network :public_network

  config.vm.synced_folder "../salt_roots", "/srv"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end
  
  config.vm.provision :salt do |salt|
    salt.minion_config = "../minion"
    salt.run_highstate = true
  end

end
